CREATE TABLE `disk_tree_info` (
	`TREE_ID` CHAR(36) NOT NULL,
	`PARENT_ID` CHAR(36) NULL DEFAULT NULL COMMENT '父id',
	`TREE_NAME` VARCHAR(1000) NULL DEFAULT NULL COMMENT '树名称',
	`TREE_LEFT` INT(10) NULL DEFAULT NULL COMMENT '树左值',
	`TREE_RIGHT` INT(10) NULL DEFAULT NULL COMMENT '树右值',
	PRIMARY KEY (`TREE_ID`)
)
COMMENT='云盘目录信息'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE `disk_file_info` (
	`FILE_ID` CHAR(36) NOT NULL,
	`FILE_TREE_ID` CHAR(36) NULL DEFAULT NULL COMMENT '对应的目录id',
	`FILE_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '文件名称',
	`FILE_PATH` VARCHAR(2000) NULL DEFAULT NULL COMMENT '文件对应的路径',
	`CREATED_TIME` DATETIME NULL DEFAULT NULL COMMENT '文件生成时间',
	`SYSTIME` DATETIME NULL DEFAULT NULL COMMENT '文件上传的时间',
	`COMMENT` VARCHAR(2000) NULL DEFAULT NULL COMMENT '备注',
	PRIMARY KEY (`FILE_ID`)
)
COMMENT='云盘文件信息表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

