CREATE TABLE `app_daily_cost_info` (
	`COST_ID` CHAR(36) NOT NULL,
	`TITLE` VARCHAR(200) NULL DEFAULT NULL COMMENT '标题',
	`COST_TIME` DATETIME NULL DEFAULT NULL COMMENT '消费日期',
	`PAY_MONEY` DECIMAL(18,4) NULL DEFAULT NULL COMMENT '消费金额',
	`TYPE_DETAIL_ID` CHAR(36) NULL DEFAULT NULL COMMENT '支付类型，对应app_type_detail表的主键',
	`SYS_TIME` DATETIME NULL DEFAULT NULL COMMENT '编制日期',
	PRIMARY KEY (`COST_ID`)
)
COMMENT='日常消费记录'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
