CREATE TABLE `app_daily_cost_info` (
	`COST_ID` CHAR(36) NOT NULL,
	`TITLE` VARCHAR(200) NULL DEFAULT NULL COMMENT '标题',
	`COST_TIME` DATETIME NULL DEFAULT NULL COMMENT '消费日期',
	`PAY_MONEY` DECIMAL(18,4) NULL DEFAULT NULL COMMENT '消费金额',
	`TYPE_DETAIL_ID` DECIMAL(18,4) NULL DEFAULT NULL COMMENT '支付类型，对应app_type_detail表的主键',
	`SYS_TIME` DATETIME NULL DEFAULT NULL COMMENT '编制日期',
	PRIMARY KEY (`COST_ID`)
)
COMMENT='日常消费记录'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `app_note_info` (
	`NOTE_ID` CHAR(36) NOT NULL,
	`TYPE_DETAIL_ID` CHAR(36) NOT NULL COMMENT '笔记类型，对应app_type_detail表主键',
	`TITLE` VARCHAR(200) NOT NULL COMMENT '笔记标题',
	`CONTENT` VARCHAR(2000) NOT NULL COMMENT '笔记内容',
	`SYS_TIME` DATETIME NOT NULL COMMENT '编制日期',
	`MEMBER_ID` CHAR(36) NOT NULL COMMENT '编制人，对应core_member_info表的主键',
	PRIMARY KEY (`NOTE_ID`)
)
COMMENT='笔记或日记表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `app_type_info` (
	`TYPE_ID` CHAR(36) NOT NULL,
	`TYPE_NAME` VARCHAR(100) NOT NULL COMMENT '笔记类型、日常消费类型、支付方式、、等',
	`TYPE_CODE` VARCHAR(50) NOT NULL COMMENT '类型编码',
	`SYS_TIME` DATETIME NOT NULL COMMENT '编制时间',
	`MEMBER_ID` CHAR(36) NOT NULL COMMENT '编制人，对应core_member_info表主键',
	PRIMARY KEY (`TYPE_ID`)
)
COMMENT='各种类型的统一表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `core_member_info` (
	`MEMBER_ID` CHAR(36) NOT NULL COMMENT '用户编号',
	`MEMBER_NAME` VARCHAR(100) NOT NULL COMMENT '用户名称',
	`PHOTO` LONGBLOB NULL COMMENT '用户头像',
	`ACCOUNT` VARCHAR(50) NOT NULL COMMENT '登录账号',
	`PASSWORD` VARCHAR(200) NOT NULL COMMENT '登录密码',
	`IS_FROZEN` BIT(1) NOT NULL COMMENT '是否冻结',
	PRIMARY KEY (`MEMBER_ID`)
)
COMMENT='人员信息表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
CREATE TABLE `core_menu_tree_info` (
	`MENU_ID` CHAR(36) NOT NULL,
	`MENU_LEVEL` INT(11) NULL DEFAULT NULL COMMENT '同级顺序',
	`OUTLINE_LEVEL` VARCHAR(200) NULL DEFAULT NULL COMMENT '大纲序号',
	`TITLE` VARCHAR(100) NULL DEFAULT NULL COMMENT '菜单标题',
	`CODE` VARCHAR(100) NULL DEFAULT NULL COMMENT '菜单编码',
	`URL` VARCHAR(1000) NULL DEFAULT NULL COMMENT '菜单路径',
	`ICON` VARCHAR(200) NULL DEFAULT NULL COMMENT '菜单图标',
	PRIMARY KEY (`MENU_ID`)
)
COMMENT='树形菜单列表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
