ALTER TABLE `app_type_detail`
	ALTER `DETAIL_NAME` DROP DEFAULT;
ALTER TABLE `app_type_detail`
	CHANGE COLUMN `DETAIL_NAME` `DETAIL_NAME` VARCHAR(100) NOT NULL COMMENT '详细类型名称' AFTER `TYPE_ID`,
	ADD COLUMN `DETAIL_VALUE` VARCHAR(50) NOT NULL COMMENT '值' AFTER `DETAIL_CODE`,
	ADD COLUMN `DETAIL_LEVEL` INT NOT NULL COMMENT '顺序' AFTER `DETAIL_VALUE`;
